---
- name: Ensure required variables are set
  ansible.builtin.assert:
    that:
    - remote_ignore_ips is defined
    # assert is list
    - remote_ignore_ips is not string and remote_ignore_ips is not mapping and remote_ignore_ips is iterable
    - remote_ignore_ips | length > 0
    - remote_ignore_ips | reject('defined') | length == 0
    - f2b_jails is defined
    # assert is list
    - f2b_jails is not string and f2b_jails is not mapping and f2b_jails is iterable
    - f2b_jails | length > 0
    - f2b_jails | rejectattr('dest', 'defined') | length == 0
    - f2b_jails | rejectattr('dest', 'string') | length == 0
- name: Ensure fail2ban installed
  become: yes
  ansible.builtin.apt:
    name:
    - fail2ban
    state: present
- name: Add fail2ban defaults
  become: yes
  ansible.builtin.template:
    dest: /etc/fail2ban/jail.local
    group: root
    mode: "0644"
    owner: root
    src: jail.local.j2
  notify: Reload fail2ban
- name: Configure fail2ban jails (at least one is required)
  become: yes
  notify: Reload fail2ban
  ansible.builtin.template:
    dest: /etc/fail2ban/jail.d/{{ item.dest }}.local
    group: root
    mode: "0644"
    owner: root
    src: extra_jail.local.j2
  loop: "{{ f2b_jails }}"
  loop_control:
    label: "{{ item.dest }}"
...
